### PR TITLE
Example 15 unitsquare2 poisson

### PR DESCRIPTION
**Pull request by PhilippeRicka**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/feelpp/toolbox/pulls) for the same change?
- [ ] Have you fixed a Bug ?
- [x] Have you added the documentation of the example or benchmark ?
- [x] Have you successfully run the example or benchmark?
- [x] Have you documented the results?
- [x] Have you added the images to the documentation?
- [ ] Have you added the vtkjs files for 3D visualization in the documentation?
- [ ] Have you added the vtkjs files to a Data Management Plateform _e.g_ https://girder.math.unistra.fr

-----

### CODE REVIEW

**Comment by prudhomm** [comment]
@PhilippeRicka there is a conflict please fix it

**Comment by prudhomm** [comment]
It looks nicer but on
http://docs.feelpp.org/cases/0.105-case-15-unitsquare2-poisson/poisson/usquare/README/
 - images are are now shown
 - links are not set properly (look at other examples and antora docs)
 - there is a big white  space at the bottom

**Comment by prudhomm** [comment]
@PhilippeRicka links and images are not working

**Comment by prudhomm** [comment]
@PhilippeRicka what should be done with this PR ? it seems broken

**Comment by PhilippeRicka** [comment]
Actually, this one can simply be deleted. The 2Dchannel branch contains more recent updates of unitsquare testcase doc. I just made a mistake using git.

**Pull request closed without merging**
