### PR TITLE
Example 48 airbus

### PR DESCRIPTION
**Pull request by jbwahl**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/feelpp/toolbox/pulls) for the same change?
- [ ] Have you fixed a Bug ?
- [x] Have you added the documentation of the example or benchmark ?
- [x] Have you successfully run the example or benchmark?
- [ ] Have you documented the results?
- [x] Have you added the images to the documentation?
- [ ] Have you added the vtkjs files for 3D visualization in the documentation?
- [ ] Have you added the vtkjs files to a Data Management Plateform _e.g_ https://girder.math.unistra.fr

-----

### CODE REVIEW

**Comment by jbwahl** [comment]
@prudhomm it's not finished but a first pull request could be nice to fix the links.

**Comment by prudhomm** [comment]
it seems the command line is buggy (heat1fluid instead of heatfluid)

**Comment by jbwahl** [comment]
right ! i fix that

**Comment by jbwahl** [comment]
@prudhomm it seems good now. 
3D can't be run for now because of the prec, but the commands are ok

**Comment by jbwahl** [comment]
@prudhomm can we merge ?

**Pull request merged**
